server:
  port: 8080
spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: telemetry-service
              uri: http://localhost:8081
              predicates:
                - Path=/telemetry/**
              filters:
                - StripPrefix=1
            - id: decision-service
              uri: http://localhost:8082
              predicates:
                - Path=/decisions/**
              filters:
                - StripPrefix=1
            - id: assets-service
              uri: http://localhost:8083
              predicates:
                - Path=/assets/**
              filters:
                - StripPrefix=1
            - id: users-service
              uri: http://localhost:8084
              predicates:
                - Path=/users/**
              filters:
                - StripPrefix=1
