server:
  port: 8080
spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: assets-service
              uri: http://localhost:8083
              predicates:
                - Path=/assets/**
              filters:
                - StripPrefix=1
